# 기본 세팅

In [9]:
%cd C:\\Users\\User\\Desktop\\boot camp\\data

C:\Users\User\Desktop\boot camp\data


In [4]:
import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('fivethirtyeight')
plt.ion()

import warnings
warnings.filterwarnings('ignore')


In [5]:
import matplotlib as mpl
# Add every font at the specified location
font_dir = ['./fonts']
for font in mpl.font_manager.findSystemFonts(fontpaths=font_dir):
 print(mpl.font_manager.FontProperties(fname=font).get_name())
 mpl.font_manager.fontManager.addfont(font)

NanumGothicOTF Eco
D2Coding
NanumGothic Eco
NanumBarunGothic
NanumGothicOTF
NanumMyeongjoOTF Eco
NanumGothicOTF
Nanum Pen Script OTF
NanumSquareOTF
Noto Sans KR
NanumMyeongjo Eco
NanumSquare
NanumSquare_ac
NanumSquareRound
Noto Sans KR
NanumSquareRound
Nanum Pen Script
NanumSquare
Nanum Brush Script OTF
NanumGothic
NanumBarunGothic
NanumMyeongjo YetHangul
NanumMyeongjo Eco
Noto Sans KR
D2Coding ligature
NanumBarunpenOTF
NanumSquareRoundOTF
NanumGothic Eco
NanumGothic
Noto Sans KR
NanumMyeongjo
NanumSquare Neo Regular
NanumMyeongjoOTF
NanumSquareOTF
NanumMyeongjoOTF Eco
NanumSquare Neo Light
NanumGothicOTF
NanumBarunGothic
NanumSquare Neo OTF Bold
NanumSquare Neo OTF ExtraBold
NanumGothic
NanumSquareRoundOTF
D2Coding ligature
NanumBarunGothicOTF
D2Coding ligature
NanumSquareOTF
NanumBarunGothic
NanumSquareOTF_ac
NanumGothic
NanumSquare
NanumBarunGothicOTF
NanumBarunGothic YetHangul
NanumSquareOTF
NanumSquareRound
NanumMyeongjo
NanumSquareRound
NanumMyeongjoOTF YetHangul
NanumSquareOTF_a

In [6]:
# 시스템 폰트 경로 리스트
font_list = mpl.font_manager.findSystemFonts()
print(font_list)
# 폰트 설정하기
prop = mpl.font_manager.FontProperties(fname='원하는 폰트 경로')
plt.rcParams['font.family'] = prop.get_family()

['C:\\Windows\\Fonts\\HancomEQN.ttf', 'C:\\Windows\\Fonts\\ariali.ttf', 'C:\\Windows\\Fonts\\arialbd.ttf', 'C:\\Windows\\Fonts\\REFSAN.TTF', 'C:\\Windows\\Fonts\\malgun.ttf', 'C:\\Windows\\Fonts\\GOTHICBI.TTF', 'C:\\Windows\\Fonts\\msjhl.ttc', 'C:\\Windows\\Fonts\\MTEXTRA.TTF', 'C:\\Windows\\Fonts\\BKANT.TTF', 'C:\\Windows\\Fonts\\HANDotumB.ttf', 'C:\\Windows\\Fonts\\mmrtext.ttf', 'C:\\Windows\\Fonts\\msyi.ttf', 'C:\\Windows\\Fonts\\HMFMOLD.TTF', 'C:\\Windows\\Fonts\\batang.ttc', 'C:\\Windows\\Fonts\\NirmalaS.ttf', 'C:\\Windows\\Fonts\\comici.ttf', 'C:\\Users\\User\\AppData\\Local\\Microsoft\\Windows\\Fonts\\Cafe24Ohsquare.ttf', 'C:\\Windows\\Fonts\\DUBAI-BOLD.TTF', 'C:\\Windows\\Fonts\\couri.ttf', 'C:\\Windows\\Fonts\\LEELAWDB.TTF', 'C:\\Windows\\Fonts\\WINGDNG2.TTF', 'C:\\Windows\\Fonts\\segoeui.ttf', 'C:\\Windows\\Fonts\\WINGDNG3.TTF', 'C:\\Windows\\Fonts\\timesbd.ttf', 'C:\\Windows\\Fonts\\ARIALN.TTF', 'C:\\Windows\\Fonts\\msjh.ttc', 'C:\\Windows\\Fonts\\constanz.ttf', 'C:\\Windows

In [7]:
# Set font family globally
mpl.rcParams['font.family'] = 'Noto Sans KR'
print(mpl.rcParams['font.family'])

['Noto Sans KR']


## 데이터 로드

In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from lightgbm import LGBMClassifier

SEED = 42

In [11]:
df = pd.read_csv('Titanic.csv')

In [13]:
df.columns = [col.lower() for col in df.columns] # 컬럼명 소문자로 변환
df.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [14]:
y_train = df["survived"] # 정답값
df = df.drop('survived', axis=1) # 정답값 제외
df.shape, y_train.shape

((891, 11), (891,))

In [15]:
# 결측치 미리 채우기
df.age = df.age.fillna(df.age.median()) # age 중앙값
df.fare = df.fare.fillna(df.fare.median()) # fare 중앙값
df.cabin = df.cabin.fillna("UNK") # cabin 임의의 문자열로 채우기
df.embarked = df.embarked.fillna(df.embarked.mode()[0]) # embarked 최빈값

In [16]:
# 학습에 바로 사용가능한 특성
cols = ["pclass","age","sibsp","parch","fare"]
features = df[cols]

In [17]:
print(f'before: {df.shape}')
# 범주형 one-hot encoding
cols = ["sex","embarked","ticket","cabin"]
enc = OneHotEncoder()
sparse_features = pd.DataFrame(
    enc.fit_transform(df[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
x_train = pd.concat([features,sparse_features],axis=1) # 특성
print(f'after: {x_train.shape}')
x_train.head()

before: (891, 11)
after: (891, 839)


pclass   age  sibsp  parch     fare  sex_female  sex_male  embarked_C  \
0       3  22.0      1      0   7.2500         0.0       1.0         0.0   
1       1  38.0      1      0  71.2833         1.0       0.0         1.0   
2       3  26.0      0      0   7.9250         1.0       0.0         0.0   
3       1  35.0      1      0  53.1000         1.0       0.0         0.0   
4       3  35.0      0      0   8.0500         0.0       1.0         0.0   

   embarked_Q  embarked_S  ...  cabin_F E69  cabin_F G63  cabin_F G73  \
0         0.0         1.0  ...          0.0          0.0          0.0   
1         0.0         0.0  ...          0.0          0.0          0.0   
2         0.0         1.0  ...          0.0          0.0          0.0   
3         0.0         1.0  ...          0.0          0.0          0.0   
4         0.0         1.0  ...          0.0          0.0          0.0   

   cabin_F2  cabin_F33  cabin_F38  cabin_F4  cabin_G6  cabin_T  cabin_UNK  
0       0.0        0.0        0.0       0.0       0.0      0.0        1.0  
1       0.0        0.0        0.0       0.0       0.0      0.0        0.0  
2       0.0        0.0        0.0       0.0       0.0      0.0        1.0  
3       0.0        0.0        0.0       0.0       0.0      0.0        0.0  
4       0.0        0.0        0.0       0.0       0.0      0.0        1.0  

[5 rows x 839 columns]

In [18]:
model = LGBMClassifier(random_state=SEED)
cv = KFold(n_splits=5,shuffle=True,random_state=SEED)

scores = cross_val_score(model, x_train, y_train, cv = cv , scoring="roc_auc", n_jobs=-1)
base_score = scores.mean()
base_score

0.8766894920348889

## 주성분 분석

In [19]:
from sklearn.decomposition import PCA

In [20]:
pca = PCA(n_components=sparse_features.shape[1],random_state=SEED)
pca.fit(sparse_features)
sum(pca.explained_variance_ratio_)

1.0000000000000218

In [21]:
features

pclass   age  sibsp  parch     fare
0         3  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         3  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         3  35.0      0      0   8.0500
..      ...   ...    ...    ...      ...
886       2  27.0      0      0  13.0000
887       1  19.0      0      0  30.0000
888       3  28.0      1      2  23.4500
889       1  26.0      0      0  30.0000
890       3  32.0      0      0   7.7500

[891 rows x 5 columns]

In [22]:
tmp = pd.DataFrame(pca.transform(sparse_features)).add_prefix('pca_')
x_train = pd.concat([features,tmp],axis=1) # features(수치형) , tmp(압축)
print(f'after: {x_train.shape}')

after: (891, 839)


In [23]:
model = LGBMClassifier(random_state=SEED)
scores = cross_val_score(model,x_train,y_train,cv = cv, scoring='roc_auc',n_jobs=-1)
print(f'score: {scores.mean()} / base_score : {base_score}')

score: 0.887485828885578 / base_score : 0.8766894920348889


In [25]:
# 주성분 200인 경우
pca200 = PCA(n_components=200,random_state=SEED)
pca200.fit(sparse_features)
sum(pca200.explained_variance_ratio_) #주성분 분산 비율


0.7444941408409617

In [26]:
tmp = pd.DataFrame(pca200.transform(sparse_features)).add_prefix('pca_')
x_train = pd.concat([features,tmp],axis=1)
print(f'after : {x_train.shape}')

after : (891, 205)


In [27]:
model = LGBMClassifier(random_state=SEED)
scores = cross_val_score(model,x_train,y_train,cv = cv , scoring="roc_auc",n_jobs=-1)
print(f'score: {scores.mean()} / base_score: {base_score}')

score: 0.8765437939614072 / base_score: 0.8766894920348889


In [28]:
pca400 = PCA(n_components=400,random_state=SEED)
pca400.fit(sparse_features)
# 주성분에 의해 설명되는 분산비율
sum(pca400.explained_variance_ratio_)

0.8514220959331701

In [29]:
tmp = pd.DataFrame(pca400.transform(sparse_features)).add_prefix("pca_")
x_train = pd.concat([features,tmp],axis=1)
print(f'after: {x_train.shape}')

after: (891, 405)


In [30]:
model = LGBMClassifier(random_state=SEED)
scores = cross_val_score(model,x_train,y_train,cv = cv , scoring="roc_auc",n_jobs=-1)
print(f'score: {scores.mean()} / base_score: {base_score}')

score: 0.8802078129009843 / base_score: 0.8766894920348889


## 특이값 분해

In [32]:
np.random.seed(121)
a = np.random.randn(4,4)
np.round(a,3)

array([[-0.212, -0.285, -0.574, -0.44 ],
       [-0.33 ,  1.184,  1.615,  0.367],
       [-0.014,  0.63 ,  1.71 , -1.327],
       [ 0.402, -0.191,  1.404, -1.969]])

In [34]:
from numpy.linalg import svd

U, Sigma, Vt = svd(a) # 특이값 분행

print(U.shape, Sigma.shape, Vt.shape)
print('U matrix:\n',np.round(U, 3))
print('Sigma Value:\n',np.round(Sigma, 3))
print('V transpose matrix:\n',np.round(Vt, 3))

(4, 4) (4,) (4, 4)
U matrix:
 [[-0.079 -0.318  0.867  0.376]
 [ 0.383  0.787  0.12   0.469]
 [ 0.656  0.022  0.357 -0.664]
 [ 0.645 -0.529 -0.328  0.444]]
Sigma Value:
 [3.423 2.023 0.463 0.079]
V transpose matrix:
 [[ 0.041  0.224  0.786 -0.574]
 [-0.2    0.562  0.37   0.712]
 [-0.778  0.395 -0.333 -0.357]
 [-0.593 -0.692  0.366  0.189]]


In [35]:
# Sima를 다시 0 을 포함한 대칭행렬로 변환
Sigma_mat = np.diag(Sigma)
a_ = np.dot(np.dot(U, Sigma_mat), Vt)
print(f'원본: {np.round(a,3)}')
print('-'*50)
print(f'복원: {np.round(a_, 3)}')

원본: [[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]
--------------------------------------------------
복원: [[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


### 예제

In [38]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=100,random_state=SEED)
svd.fit(sparse_features)
sum(svd.explained_variance_ratio_)

0.6467003948429448

In [39]:
tmp = pd.DataFrame(svd.transform(sparse_features)).add_prefix("svd_")
#svd는 모든 컬럼에 붙임
x_train = pd.concat([features,tmp],axis=1)
print(f'after: {x_train.shape}')

after: (891, 105)


In [40]:
model = LGBMClassifier(random_state=SEED)
scores = cross_val_score(model,x_train,y_train,cv = cv , scoring="roc_auc",n_jobs=-1)
print(f'score: {scores.mean()} / base_score: {base_score}')

score: 0.8928809149552777 / base_score: 0.8766894920348889


## 비음수 행렬 분해

In [45]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=100,random_state=SEED,max_iter=500)
nmf.fit(sparse_features)

NMF(max_iter=500, n_components=100, random_state=42)

In [44]:
(nmf.componets_ <=0),sum() , nmf.componets_.shape

NameError: name 'nmf' is not defined